# API some country info  _______________

In [1]:
### imports
import requests

import matplotlib.pyplot as plt
import json
import pandas as pd

In [2]:
### configuratories
gdp_endpoint = 'https://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.PP.KD?format=json&per_page=20000'
life_endpoint = 'https://api.worldbank.org/v2/country/all/indicator/SP.DYN.LE00.IN?format=json&per_page=20000'
country_info_endpoint = 'https://api.worldbank.org/v2/country?format=json&per_page=20000'
USA_country_info_endpoint = 'https://api.worldbank.org/v2/country/us?format=json'

### bonus
### 1: only usa
USA_gdp_endpoint = 'https://api.worldbank.org/v2/country/USA/indicator/NY.GDP.PCAP.PP.KD?format=json&per_page=20000'
USA_life_endpoint = 'https://api.worldbank.org/v2/country/USA/indicator/SP.DYN.LE00.IN?format=json&per_page=20000'
### 2: only usa 2021
USA2021_gdp_endpoint = 'https://api.worldbank.org/v2/country/USA/indicator/NY.GDP.PCAP.PP.KD?format=json&date=2021&per_page=20000'
USA2021_life_endpoint = 'https://api.worldbank.org/v2/country/USA/indicator/SP.DYN.LE00.IN?format=json&date=2021&per_page=20000'
### 3: only usa 2000-2021
USA2020_2021_gdp_endpoint = 'https://api.worldbank.org/v2/country/USA/indicator/NY.GDP.PCAP.PP.KD?format=json&date=2000:2021&per_page=20000'
USA2020_2021_life_endpoint = 'https://api.worldbank.org/v2/country/USA/indicator/SP.DYN.LE00.IN?format=json&date=2000:2021&per_page=20000'
### 4: only usa:can 2000-2021
USACAN2020_2021_gdp_endpoint = 'https://api.worldbank.org/v2/country/usa;can/indicator/NY.GDP.PCAP.PP.KD?format=json&date=2000:2021&per_page=2000'
USACAN2020_2021_life_endpoint = 'https://api.worldbank.org/v2/country/usa;can/indicator/SP.DYN.LE00.IN?format=json&date=2000:2021&per_page=20000'


indicators = 'https://api.worldbank.org/v2/indicator?format=json&per_page=30000'

# all country

In [3]:
### what we wanna look up - GDP per capita, PPP (constant 2017 international $)
response = requests.get(gdp_endpoint)
r = response.json()

### make df - the first row is metadata not intended for df
data = r[1]
gdp_df = pd.json_normalize(data)

gdp_df

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,AFE,2025,NaN,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
1,AFE,2024,4106.434140,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
2,AFE,2023,4083.993003,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
3,AFE,2022,4106.501907,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
4,AFE,2021,4056.113017,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZH,Africa Eastern and Southern
...,...,...,...,...,...,...,...,...,...,...
17551,ZWE,1964,NaN,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZW,Zimbabwe
17552,ZWE,1963,NaN,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZW,Zimbabwe
17553,ZWE,1962,NaN,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZW,Zimbabwe
17554,ZWE,1961,NaN,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZW,Zimbabwe
17555,ZWE,1960,NaN,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",ZW,Zimbabwe

In [4]:
### what we wanna look up - Life expectancy at birth, total (years)
response = requests.get(life_endpoint)
r = response.json()

### make df - the first row is metadata not intended for df
data = r[1]
life_df = pd.json_normalize(data)

### drops
life_df = life_df.dropna(subset=['value'])

life_df

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
1,AFE,2024,65.349930,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern
2,AFE,2023,65.146228,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern
3,AFE,2022,64.487152,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern
4,AFE,2021,62.979999,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern
5,AFE,2020,63.766484,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZH,Africa Eastern and Southern
...,...,...,...,...,...,...,...,...,...,...
17551,ZWE,1964,55.431000,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZW,Zimbabwe
17552,ZWE,1963,54.942000,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZW,Zimbabwe
17553,ZWE,1962,54.453000,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZW,Zimbabwe
17554,ZWE,1961,53.966000,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZW,Zimbabwe
17555,ZWE,1960,53.492000,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",ZW,Zimbabwe

In [5]:
### format our life_df for merging
life_df.columns = life_df.columns.str.replace('.', '_')

life_df = life_df[[
    'country_value',
    'countryiso3code',
    'date',
    'value'
]]

life_df = life_df.rename(columns={
    'value': 'life_expectancy',
    'country_value': 'country'
})

### format our gdp_df for merging
gdp_df.columns = gdp_df.columns.str.replace('.', '_')

gdp_df = gdp_df.dropna(subset=['value'])

gdp_df = gdp_df[[
    'country_value',
    'countryiso3code',
    'country_id',
    'date',
    'value'
]]

gdp_df = gdp_df.rename(columns={
    'value': 'gdp',
    'country_value': 'country'
})

In [6]:
### merge and format the 2 df into gdp_life_df
gdp_life_df = life_df.merge(gdp_df, 'inner', ['countryiso3code', 'date'])
gdp_life_df = gdp_life_df.rename(columns={"country_x": "country"}).drop(columns=["country_y"])
gdp_life_df = gdp_life_df[['country', 'countryiso3code', 'country_id', 'date', 'gdp', 'life_expectancy']]
gdp_life_df

,country,countryiso3code,country_id,date,gdp,life_expectancy
0,Africa Eastern and Southern,AFE,ZH,2024,4106.434140,65.349930
1,Africa Eastern and Southern,AFE,ZH,2023,4083.993003,65.146228
2,Africa Eastern and Southern,AFE,ZH,2022,4106.501907,64.487152
3,Africa Eastern and Southern,AFE,ZH,2021,4056.113017,62.979999
4,Africa Eastern and Southern,AFE,ZH,2020,3978.931395,63.766484
...,...,...,...,...,...,...
8880,Zimbabwe,ZWE,ZW,1994,6010.742417,52.537000
8881,Zimbabwe,ZWE,ZW,1993,5509.083113,53.976000
8882,Zimbabwe,ZWE,ZW,1992,5532.037403,55.602000
8883,Zimbabwe,ZWE,ZW,1991,6254.274735,57.037000
8884,Zimbabwe,ZWE,ZW,1990,6082.842451,58.319000

In [7]:
### what we wanna look up - all country info
response = requests.get(country_info_endpoint)
r = response.json()

### make df - the first row is metadata not intended for df
data = r[1]
country_df = pd.json_normalize(data)

### looks like any row that doesnt have lat or lon is an aggregate/non-country
country_df = country_df[country_df['longitude'] != '']

country_df = country_df.rename(columns={"name": "country", "capitalCity": "capital_city", "iso2Code":"iso2code"})
country_df

,id,iso2code,country,capital_city,longitude,latitude,region.id,region.iso2code,region.value,adminregion.id,adminregion.iso2code,adminregion.value,incomeLevel.id,incomeLevel.iso2code,incomeLevel.value,lendingType.id,lendingType.iso2code,lendingType.value
0,ABW,AW,Aruba,Oranjestad,-70.0167,12.5167,LCN,ZJ,Latin America & Caribbean,,,,HIC,XD,High income,LNX,XX,Not classified
2,AFG,AF,Afghanistan,Kabul,69.1761,34.5228,MEA,ZQ,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
5,AGO,AO,Angola,Luanda,13.242,-8.81155,SSF,ZG,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IBD,XF,IBRD
6,ALB,AL,Albania,Tirane,19.8172,41.3317,ECS,Z7,Europe & Central Asia,ECA,7E,Europe & Central Asia (excluding high income),UMC,XT,Upper middle income,IBD,XF,IBRD
7,AND,AD,Andorra,Andorra la Vella,1.5218,42.5075,ECS,Z7,Europe & Central Asia,,,,HIC,XD,High income,LNX,XX,Not classified
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290,XKX,XK,Kosovo,Pristina,20.926,42.565,ECS,Z7,Europe & Central Asia,ECA,7E,Europe & Central Asia (excluding high income),UMC,XT,Upper middle income,IDX,XI,IDA
292,YEM,YE,"Yemen, Rep.",Sana'a,44.2075,15.352,MEA,ZQ,"Middle East, North Africa, Afghanistan & Pakistan",MNA,XQ,"Middle East, North Africa, Afghanistan & Pakis...",LIC,XM,Low income,IDX,XI,IDA
293,ZAF,ZA,South Africa,Pretoria,28.1871,-25.746,SSF,ZG,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),UMC,XT,Upper middle income,IBD,XF,IBRD
294,ZMB,ZM,Zambia,Lusaka,28.2937,-15.3982,SSF,ZG,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDX,XI,IDA
295,ZWE,ZW,Zimbabwe,Harare,31.0672,-17.8312,SSF,ZG,Sub-Saharan Africa,SSA,ZF,Sub-Saharan Africa (excluding high income),LMC,XN,Lower middle income,IDB,XH,Blend

In [8]:
### merge and format that thang
gdp_life_country_df = gdp_life_df.merge(country_df, 'inner', 'country')

gdp_life_country_df = gdp_life_country_df.rename(columns={"countryiso3code":"iso3code"}).drop(columns=['id', 'country_id'])
gdp_life_country_df = gdp_life_country_df[[
    "country",
    "date",
    "gdp",
    "life_expectancy",
    "capital_city",
    "incomeLevel.value",
    "adminregion.value",
    "iso2code",
    "iso3code",
    
]]
gdp_life_country_df

,country,date,gdp,life_expectancy,capital_city,incomeLevel.value,adminregion.value,iso2code,iso3code
0,Afghanistan,2023,1983.812620,66.035,Kabul,Low income,"Middle East, North Africa, Afghanistan & Pakis...",AF,AFG
1,Afghanistan,2022,1981.710168,65.617,Kabul,Low income,"Middle East, North Africa, Afghanistan & Pakis...",AF,AFG
2,Afghanistan,2021,2144.166570,60.417,Kabul,Low income,"Middle East, North Africa, Afghanistan & Pakis...",AF,AFG
3,Afghanistan,2020,2769.685745,61.454,Kabul,Low income,"Middle East, North Africa, Afghanistan & Pakis...",AF,AFG
4,Afghanistan,2019,2927.245144,62.941,Kabul,Low income,"Middle East, North Africa, Afghanistan & Pakis...",AF,AFG
...,...,...,...,...,...,...,...,...,...
6708,Zimbabwe,1994,6010.742417,52.537,Harare,Lower middle income,Sub-Saharan Africa (excluding high income),ZW,ZWE
6709,Zimbabwe,1993,5509.083113,53.976,Harare,Lower middle income,Sub-Saharan Africa (excluding high income),ZW,ZWE
6710,Zimbabwe,1992,5532.037403,55.602,Harare,Lower middle income,Sub-Saharan Africa (excluding high income),ZW,ZWE
6711,Zimbabwe,1991,6254.274735,57.037,Harare,Lower middle income,Sub-Saharan Africa (excluding high income),ZW,ZWE
6712,Zimbabwe,1990,6082.842451,58.319,Harare,Lower middle income,Sub-Saharan Africa (excluding high income),ZW,ZWE

# USA and CAN from 2000:2021

### swapping endpoint vars gets 2021, 2000-2021, USA and CAN 2000-2021

In [13]:
### what we wanna look up - GDP per capita, PPP (constant 2017 international $)
response = requests.get(USACAN2020_2021_gdp_endpoint)
r = response.json()

### make df - the first row is metadata not intended for df
data = r[1]
usa_can_gdp_df = pd.json_normalize(data)

usa_can_gdp_df

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,CAN,2021,56995.117678,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
1,CAN,2020,54092.879032,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
2,CAN,2019,57583.845798,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
3,CAN,2018,57337.490910,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
4,CAN,2017,56612.328537,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
5,CAN,2016,55606.154919,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
6,CAN,2015,55660.867527,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
7,CAN,2014,55723.483540,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
8,CAN,2013,54712.178424,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
9,CAN,2012,54034.803475,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
10,CAN,2011,53681.129670,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
11,CAN,2010,52558.440814,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
12,CAN,2009,51552.422384,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
13,CAN,2008,53711.679206,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
14,CAN,2007,53761.862030,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
15,CAN,2006,53195.781842,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
16,CAN,2005,52356.557804,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
17,CAN,2004,51210.679612,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
18,CAN,2003,50139.786235,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
19,CAN,2002,49695.006691,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
20,CAN,2001,48774.167553,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
21,CAN,2000,48399.305539,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",CA,Canada
22,USA,2021,71307.401728,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
23,USA,2020,67342.070929,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
24,USA,2019,69112.602689,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
25,USA,2018,67719.765639,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
26,USA,2017,66155.555568,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
27,USA,2016,65017.654964,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
28,USA,2015,64359.472590,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
29,USA,2014,63018.803394,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
30,USA,2013,61958.723442,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
31,USA,2012,61134.530609,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
32,USA,2011,60245.484399,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
33,USA,2010,59789.412907,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
34,USA,2009,58714.973692,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
35,USA,2008,60798.433840,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
36,USA,2007,61306.596939,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
37,USA,2006,60676.565569,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
38,USA,2005,59604.753637,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
39,USA,2004,58131.633685,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
40,USA,2003,56498.207831,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
41,USA,2002,55436.116981,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
42,USA,2001,55017.304979,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States
43,USA,2000,55038.622496,,,0,NY.GDP.PCAP.PP.KD,"GDP per capita, PPP (constant 2021 internation...",US,United States

In [14]:
### what we wanna look up - Life expectancy at birth, total (years)
response = requests.get(USACAN2020_2021_life_endpoint)
r = response.json()

### make df - the first row is metadata not intended for df
data = r[1]
usa_can_life_df = pd.json_normalize(data)

usa_can_life_df

,countryiso3code,date,value,unit,obs_status,decimal,indicator.id,indicator.value,country.id,country.value
0,CAN,2021,81.451463,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
1,CAN,2020,81.530000,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
2,CAN,2019,82.158537,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
3,CAN,2018,81.803659,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
4,CAN,2017,81.807805,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
5,CAN,2016,81.940000,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
6,CAN,2015,81.825854,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
7,CAN,2014,81.784390,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
8,CAN,2013,81.744878,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
9,CAN,2012,81.663659,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
10,CAN,2011,81.482683,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
11,CAN,2010,81.322195,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
12,CAN,2009,81.066098,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
13,CAN,2008,80.724634,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
14,CAN,2007,80.543659,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
15,CAN,2006,80.543659,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
16,CAN,2005,80.112683,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
17,CAN,2004,79.992195,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
18,CAN,2003,79.715122,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
19,CAN,2002,79.530732,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
20,CAN,2001,79.398049,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
21,CAN,2000,79.166829,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",CA,Canada
22,USA,2021,76.329268,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
23,USA,2020,76.980488,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
24,USA,2019,78.787805,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
25,USA,2018,78.639024,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
26,USA,2017,78.539024,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
27,USA,2016,78.539024,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
28,USA,2015,78.690244,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
29,USA,2014,78.841463,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
30,USA,2013,78.741463,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
31,USA,2012,78.741463,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
32,USA,2011,78.641463,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
33,USA,2010,78.541463,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
34,USA,2009,78.390244,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
35,USA,2008,78.039024,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
36,USA,2007,77.987805,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
37,USA,2006,77.687805,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
38,USA,2005,77.487805,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
39,USA,2004,77.487805,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
40,USA,2003,77.036585,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
41,USA,2002,76.936585,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
42,USA,2001,76.836585,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States
43,USA,2000,76.636585,,,0,SP.DYN.LE00.IN,"Life expectancy at birth, total (years)",US,United States

In [16]:
### format our life_df and gdp_df for merging
usa_can_life_df.columns = usa_can_life_df.columns.str.replace('.', '_')

usa_can_life_df = usa_can_life_df[[
    'country_value',
    'countryiso3code',
    'date',
    'value'
]]

usa_can_life_df = usa_can_life_df.rename(columns={
    'value': 'life_expectancy',
    'country_value': 'country'
})

### format our gdp_df for merging
usa_can_gdp_df.columns = usa_can_gdp_df.columns.str.replace('.', '_')

usa_can_gdp_df = usa_can_gdp_df.dropna(subset=['value'])

usa_can_gdp_df = usa_can_gdp_df[[
    'country_value',
    'countryiso3code',
    'country_id',
    'date',
    'value'
]]

usa_can_gdp_df = usa_can_gdp_df.rename(columns={
    'value': 'gdp',
    'country_value': 'country'
})

In [17]:
### merge and format the 2 df into gdp_life_df
usa_can_gdp_life_df = usa_can_life_df.merge(gdp_df, 'inner', ['countryiso3code', 'date'])
usa_can_gdp_life_df = usa_can_gdp_life_df.rename(columns={"country_x": "country"}).drop(columns=["country_y"])
usa_can_gdp_life_df = usa_can_gdp_life_df[['country', 'countryiso3code', 'country_id', 'date', 'gdp', 'life_expectancy']]
usa_can_gdp_life_df

,country,countryiso3code,country_id,date,gdp,life_expectancy
0,Canada,CAN,CA,2021,56995.117678,81.451463
1,Canada,CAN,CA,2020,54092.879032,81.530000
2,Canada,CAN,CA,2019,57583.845798,82.158537
3,Canada,CAN,CA,2018,57337.490910,81.803659
4,Canada,CAN,CA,2017,56612.328537,81.807805
5,Canada,CAN,CA,2016,55606.154919,81.940000
6,Canada,CAN,CA,2015,55660.867527,81.825854
7,Canada,CAN,CA,2014,55723.483540,81.784390
8,Canada,CAN,CA,2013,54712.178424,81.744878
9,Canada,CAN,CA,2012,54034.803475,81.663659
10,Canada,CAN,CA,2011,53681.129670,81.482683
11,Canada,CAN,CA,2010,52558.440814,81.322195
12,Canada,CAN,CA,2009,51552.422384,81.066098
13,Canada,CAN,CA,2008,53711.679206,80.724634
14,Canada,CAN,CA,2007,53761.862030,80.543659
15,Canada,CAN,CA,2006,53195.781842,80.543659
16,Canada,CAN,CA,2005,52356.557804,80.112683
17,Canada,CAN,CA,2004,51210.679612,79.992195
18,Canada,CAN,CA,2003,50139.786235,79.715122
19,Canada,CAN,CA,2002,49695.006691,79.530732
20,Canada,CAN,CA,2001,48774.167553,79.398049
21,Canada,CAN,CA,2000,48399.305539,79.166829
22,United States,USA,US,2021,71307.401728,76.329268
23,United States,USA,US,2020,67342.070929,76.980488
24,United States,USA,US,2019,69112.602689,78.787805
25,United States,USA,US,2018,67719.765639,78.639024
26,United States,USA,US,2017,66155.555568,78.539024
27,United States,USA,US,2016,65017.654964,78.539024
28,United States,USA,US,2015,64359.472590,78.690244
29,United States,USA,US,2014,63018.803394,78.841463
30,United States,USA,US,2013,61958.723442,78.741463
31,United States,USA,US,2012,61134.530609,78.741463
32,United States,USA,US,2011,60245.484399,78.641463
33,United States,USA,US,2010,59789.412907,78.541463
34,United States,USA,US,2009,58714.973692,78.390244
35,United States,USA,US,2008,60798.433840,78.039024
36,United States,USA,US,2007,61306.596939,77.987805
37,United States,USA,US,2006,60676.565569,77.687805
38,United States,USA,US,2005,59604.753637,77.487805
39,United States,USA,US,2004,58131.633685,77.487805
40,United States,USA,US,2003,56498.207831,77.036585
41,United States,USA,US,2002,55436.116981,76.936585
42,United States,USA,US,2001,55017.304979,76.836585
43,United States,USA,US,2000,55038.622496,76.636585

In [19]:
### merge and format that thang
usa_can_gdp_life_country_df = usa_can_gdp_life_df.merge(country_df, 'inner', 'country')

usa_can_gdp_life_country_df = usa_can_gdp_life_country_df.rename(columns={"countryiso3code":"iso3code"}).drop(columns=['id', 'country_id'])
usa_can_gdp_life_country_df = usa_can_gdp_life_country_df[[
    "country",
    "date",
    "gdp",
    "life_expectancy",
    "capital_city",
    "incomeLevel.value",
    "adminregion.value",
    "iso2code",
    "iso3code",
    
]]
usa_can_gdp_life_country_df

,country,date,gdp,life_expectancy,capital_city,incomeLevel.value,adminregion.value,iso2code,iso3code
0,Canada,2021,56995.117678,81.451463,Ottawa,High income,,CA,CAN
1,Canada,2020,54092.879032,81.530000,Ottawa,High income,,CA,CAN
2,Canada,2019,57583.845798,82.158537,Ottawa,High income,,CA,CAN
3,Canada,2018,57337.490910,81.803659,Ottawa,High income,,CA,CAN
4,Canada,2017,56612.328537,81.807805,Ottawa,High income,,CA,CAN
5,Canada,2016,55606.154919,81.940000,Ottawa,High income,,CA,CAN
6,Canada,2015,55660.867527,81.825854,Ottawa,High income,,CA,CAN
7,Canada,2014,55723.483540,81.784390,Ottawa,High income,,CA,CAN
8,Canada,2013,54712.178424,81.744878,Ottawa,High income,,CA,CAN
9,Canada,2012,54034.803475,81.663659,Ottawa,High income,,CA,CAN
10,Canada,2011,53681.129670,81.482683,Ottawa,High income,,CA,CAN
11,Canada,2010,52558.440814,81.322195,Ottawa,High income,,CA,CAN
12,Canada,2009,51552.422384,81.066098,Ottawa,High income,,CA,CAN
13,Canada,2008,53711.679206,80.724634,Ottawa,High income,,CA,CAN
14,Canada,2007,53761.862030,80.543659,Ottawa,High income,,CA,CAN
15,Canada,2006,53195.781842,80.543659,Ottawa,High income,,CA,CAN
16,Canada,2005,52356.557804,80.112683,Ottawa,High income,,CA,CAN
17,Canada,2004,51210.679612,79.992195,Ottawa,High income,,CA,CAN
18,Canada,2003,50139.786235,79.715122,Ottawa,High income,,CA,CAN
19,Canada,2002,49695.006691,79.530732,Ottawa,High income,,CA,CAN
20,Canada,2001,48774.167553,79.398049,Ottawa,High income,,CA,CAN
21,Canada,2000,48399.305539,79.166829,Ottawa,High income,,CA,CAN
22,United States,2021,71307.401728,76.329268,Washington D.C.,High income,,US,USA
23,United States,2020,67342.070929,76.980488,Washington D.C.,High income,,US,USA
24,United States,2019,69112.602689,78.787805,Washington D.C.,High income,,US,USA
25,United States,2018,67719.765639,78.639024,Washington D.C.,High income,,US,USA
26,United States,2017,66155.555568,78.539024,Washington D.C.,High income,,US,USA
27,United States,2016,65017.654964,78.539024,Washington D.C.,High income,,US,USA
28,United States,2015,64359.472590,78.690244,Washington D.C.,High income,,US,USA
29,United States,2014,63018.803394,78.841463,Washington D.C.,High income,,US,USA
30,United States,2013,61958.723442,78.741463,Washington D.C.,High income,,US,USA
31,United States,2012,61134.530609,78.741463,Washington D.C.,High income,,US,USA
32,United States,2011,60245.484399,78.641463,Washington D.C.,High income,,US,USA
33,United States,2010,59789.412907,78.541463,Washington D.C.,High income,,US,USA
34,United States,2009,58714.973692,78.390244,Washington D.C.,High income,,US,USA
35,United States,2008,60798.433840,78.039024,Washington D.C.,High income,,US,USA
36,United States,2007,61306.596939,77.987805,Washington D.C.,High income,,US,USA
37,United States,2006,60676.565569,77.687805,Washington D.C.,High income,,US,USA
38,United States,2005,59604.753637,77.487805,Washington D.C.,High income,,US,USA
39,United States,2004,58131.633685,77.487805,Washington D.C.,High income,,US,USA
40,United States,2003,56498.207831,77.036585,Washington D.C.,High income,,US,USA
41,United States,2002,55436.116981,76.936585,Washington D.C.,High income,,US,USA
42,United States,2001,55017.304979,76.836585,Washington D.C.,High income,,US,USA
43,United States,2000,55038.622496,76.636585,Washington D.C.,High income,,US,USA

# indicator search

In [25]:
### what we wanna look up - full indicator list
response = requests.get(indicators)
r = response.json()

### make df - the first row is metadata not intended for df
data = r[1]
ind_df = pd.json_normalize(data)

### pull only the row that has this matching column value
ind_df[ind_df['name'] == 'Public Expenditure on Education  (% GDP)']

,id,name,unit,sourceNote,sourceOrganization,topics,source.id,source.value
24993,SE.XPD.EDUC.ZS,Public Expenditure on Education (% GDP),,,,[],57,WDI Database Archives